[template]
cargo_generate_version = "<=0.23.3"
exclude = ["README.md"]
[placeholders]
plugin_name = { prompt = "Enter plugin name(in AfterFX)", default = "JK MyPlugin", type = "string" }
plugin_category = { prompt = "Enter plugin category", default = "JK Plugins F's", type = "string", choices = ["JK Plugins F's", "JK Plugins OLM", "JK Plugins Original"] }
